version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: somdul-db
    restart: always
    environment:
      POSTGRES_USER: somdul
      POSTGRES_PASSWORD: somdul_pass
      POSTGRES_DB: somdul
    ports:
      - "5434:5432"
    volumes:
      - somdul_db_data:/var/lib/postgresql/data

volumes:
  somdul_db_data:
