from datetime import date, datetime
from decimal import Decimal
from typing import Optional, List
from uuid import UUID, uuid4
from sqlalchemy import Column, Text
from sqlmodel import Field, Relationship, SQLModel

# ----------------------------------------------------
# 1. USER MODEL
# ----------------------------------------------------
class User(SQLModel, table=True):
    __tablename__ = "users"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    name: str = Field(max_length=100)
    email: str = Field(max_length=255, unique=True, index=True)
    hashed_password: str = Field(max_length=255)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Embedded in every JWT issued at login and checked on every request in
    # get_current_user — bumping this (on password change, or a future
    # "log out everywhere" action) instantly invalidates every token issued
    # before that point, since they carry the old version number. JWTs
    # otherwise have no revocation mechanism at all before their natural
    # expiry (ACCESS_TOKEN_EXPIRE_MINUTES).
    token_version: int = Field(default=0)

    # PromptPay info shown on the debtor "share slip" card. The QR is stored
    # as a base64 data URL the user uploads themselves (not generated by us)
    # — see routers/auth.py for the size cap enforced on upload.
    promptpay_account: Optional[str] = Field(default=None, max_length=100)
    promptpay_qr_data: Optional[str] = Field(default=None, sa_column=Column(Text))

    # Relationships
    wallets: List["Wallet"] = Relationship(back_populates="user", cascade_delete=True)
    credit_cards: List["CreditCard"] = Relationship(back_populates="user", cascade_delete=True)
    debtors: List["Debtor"] = Relationship(back_populates="user", cascade_delete=True)
    transactions: List["Transaction"] = Relationship(back_populates="user", cascade_delete=True)
    recurring_payments: List["RecurringPayment"] = Relationship(back_populates="user", cascade_delete=True)


# ----------------------------------------------------
# 2. WALLET MODEL
# ----------------------------------------------------
class Wallet(SQLModel, table=True):
    __tablename__ = "wallets"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    wallet_name: str = Field(max_length=100)
    wallet_type: str = Field(max_length=50) # CASH, BANK_ACCOUNT, E_WALLET
    balance: Decimal = Field(default=0.00, decimal_places=2, max_digits=15)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    user: Optional[User] = Relationship(back_populates="wallets")
    transactions: List["Transaction"] = Relationship(back_populates="wallet")


# ----------------------------------------------------
# 3. CREDIT CARD MODEL
# ----------------------------------------------------
class CreditCard(SQLModel, table=True):
    __tablename__ = "credit_cards"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    card_name: str = Field(max_length=100)
    billing_cycle_day: int = Field(default=1) # 1-31
    due_day: int = Field(default=1)          # 1-31
    credit_limit: Decimal = Field(decimal_places=2, max_digits=15)
    current_balance: Decimal = Field(default=0.00, decimal_places=2, max_digits=15)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    user: Optional[User] = Relationship(back_populates="credit_cards")
    debts: List["Debt"] = Relationship(back_populates="credit_card")
    transactions: List["Transaction"] = Relationship(back_populates="credit_card")


# ----------------------------------------------------
# 4. DEBTOR MODEL
# ----------------------------------------------------
class Debtor(SQLModel, table=True):
    __tablename__ = "debtors"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    debtor_name: str = Field(max_length=100)
    contact_info: Optional[str] = Field(default=None, max_length=255)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    user: Optional[User] = Relationship(back_populates="debtors")
    debts: List["Debt"] = Relationship(back_populates="debtor", cascade_delete=True)


# ----------------------------------------------------
# 5. DEBT MODEL
# ----------------------------------------------------
class Debt(SQLModel, table=True):
    __tablename__ = "debts"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    debtor_id: UUID = Field(foreign_key="debtors.id", ondelete="CASCADE")
    debt_type: str = Field(max_length=50) # CASH_LOAN, CREDIT_CARD_INSTALLMENT
    credit_card_id: Optional[UUID] = Field(default=None, foreign_key="credit_cards.id", ondelete="SET NULL")
    total_amount: Decimal = Field(decimal_places=2, max_digits=15)
    remaining_amount: Decimal = Field(decimal_places=2, max_digits=15)
    total_installments: int = Field(default=1)
    remaining_installments: int = Field(default=1)
    due_day: int = Field(default=1) # day of the month for recurring monthly installments
    due_date: Optional[date] = Field(default=None) # specific calendar date for one-off (non-monthly) debts — takes precedence over due_day when set
    interest_type: Optional[str] = Field(default=None, max_length=20) # None, "FLAT" (baht), "PERCENT" — display-only, never auto-applied to remaining_amount
    interest_value: Optional[Decimal] = Field(default=None, decimal_places=2, max_digits=15)
    memo: Optional[str] = Field(default=None, max_length=255)
    status: str = Field(default="UNPAID") # UNPAID, PARTIALLY_PAID, PAID
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    debtor: Optional[Debtor] = Relationship(back_populates="debts")
    credit_card: Optional[CreditCard] = Relationship(back_populates="debts")
    history: List["DebtHistory"] = Relationship(back_populates="debt", cascade_delete=True)


# ----------------------------------------------------
# 5b. DEBT HISTORY MODEL (audit log for reschedules / interest / memo edits)
# ----------------------------------------------------
class DebtHistory(SQLModel, table=True):
    __tablename__ = "debt_history"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    debt_id: UUID = Field(foreign_key="debts.id", ondelete="CASCADE")
    summary: str = Field(max_length=500) # human-readable Thai description of what changed, e.g. "เลื่อนกำหนดชำระจาก 25/07/2026 เป็น 05/08/2026"
    changed_at: datetime = Field(default_factory=datetime.utcnow, index=True)

    debt: Optional["Debt"] = Relationship(back_populates="history")


# ----------------------------------------------------
# 6. TRANSACTION MODEL (Ledge History)
# ----------------------------------------------------
class Transaction(SQLModel, table=True):
    __tablename__ = "transactions"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    tx_type: str = Field(max_length=50) # INCOME, EXPENSE
    description: str = Field(max_length=255)
    category: str = Field(max_length=50) # FOOD, REFUND, SUBSCRIPTION, etc.
    amount: Decimal = Field(decimal_places=2, max_digits=15)
    wallet_id: Optional[UUID] = Field(default=None, foreign_key="wallets.id", ondelete="SET NULL")
    credit_card_id: Optional[UUID] = Field(default=None, foreign_key="credit_cards.id", ondelete="SET NULL")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    user: Optional[User] = Relationship(back_populates="transactions")
    wallet: Optional[Wallet] = Relationship(back_populates="transactions")
    credit_card: Optional[CreditCard] = Relationship(back_populates="transactions")


# ----------------------------------------------------
# 7. RECURRING PAYMENT MODEL (Subscriptions)
# ----------------------------------------------------
class RecurringPayment(SQLModel, table=True):
    __tablename__ = "recurring_payments"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    name: str = Field(max_length=100)
    amount: Decimal = Field(decimal_places=2, max_digits=15)
    due_day: int = Field(default=1) # 1-31
    status: str = Field(default="WAITING") # WAITING, PAID
    last_paid_at: Optional[datetime] = Field(default=None) # used to auto-reset to WAITING on a new billing month
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)

    # Relationships
    user: Optional[User] = Relationship(back_populates="recurring_payments")


# ----------------------------------------------------
# 8. DISMISSED NOTIFICATION MODEL (per-user "read" state for reminder cards)
# ----------------------------------------------------
class DismissedNotification(SQLModel, table=True):
    __tablename__ = "dismissed_notifications"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    notif_id: str = Field(max_length=100, index=True) # id of the underlying debtor/card/recurring item
    dismissed_at: datetime = Field(default_factory=datetime.utcnow)


# ----------------------------------------------------
# 9. BUDGET MODEL (per-category monthly spending limit)
# ----------------------------------------------------
class Budget(SQLModel, table=True):
    __tablename__ = "budgets"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    category: str = Field(max_length=50, index=True)
    monthly_limit: Decimal = Field(decimal_places=2, max_digits=15)
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)


# ----------------------------------------------------
# 10. CATEGORY MODEL (user-editable transaction categories)
# ----------------------------------------------------
class Category(SQLModel, table=True):
    __tablename__ = "categories"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    key: str = Field(max_length=50, index=True) # stored verbatim in Transaction.category
    name: str = Field(max_length=100)
    tx_type: str = Field(max_length=20) # EXPENSE or INCOME
    icon: str = Field(max_length=50, default="fa-tag") # FontAwesome icon suffix, e.g. "fa-utensils"
    color: str = Field(max_length=30, default="slate") # Tailwind color family name, e.g. "amber"
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)


# ----------------------------------------------------
# 11. QUICK TEMPLATE MODEL (canned description+category shortcuts)
# ----------------------------------------------------
class QuickTemplate(SQLModel, table=True):
    __tablename__ = "quick_templates"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="users.id", ondelete="CASCADE")
    label: str = Field(max_length=150) # shown in the dropdown, e.g. "🍜 ข้าวกลางวัน/อาหารค่ำ"
    description: str = Field(max_length=150) # filled into the transaction's description field
    category_key: str = Field(max_length=50) # matches Category.key
    updated_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    deleted_at: Optional[datetime] = Field(default=None, index=True)
